deployments:
  dockertest:
    dockerimage: r.cfcr.io/wisedrette/wisedrette/dockertest:master
    deployment_type: kubernetes
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
    environment:
      TEST_VAL=$REGISTRY_PASSWORD
